//
// Copyright (c) Nathan Tannar
//

import SwiftUI
import Engine

/// A macro that adds the necessary components of a ``StyledView``
///
/// A ``StyledView`` is an easier way to adopt the ``ViewStyle`` API
/// to transform a `View` into one that can be styled. The `makeDefaultStyleBody(configuration:)`
/// of a ``StyledView`` will become the default style if no other style is applied.
///
/// The macro generates a `<Name>Configuration`, a `<Name>Style` protocol, a
/// `<Name>DefaultStyle`, a `<Name>StyleModifier` and a `Styled<Name>` typealias,
/// along with initializers for the view.
///
/// The configuration includes every stored instance property of the view:
/// - Generic parameters must conform to `View`, either inline or in a `where` clause,
///   and each must be the type of exactly one property. Each one becomes a ``ViewAlias``
///   in the configuration.
/// - `@Binding` properties are passed to the configuration as bindings.
/// - Properties with a default value become initializer parameters with that default.
/// - Computed, `static` and `lazy` properties, `let` constants with a value, and
///   properties that initialize themselves, such as `@State var value = 0` or
///   `@Environment(\.isEnabled) var isEnabled`, are not included.
///
/// ```
/// @StyledView
/// struct LabeledView<Label: View, Content: View>: StyledView {
///     var label: Label
///     var content: Content
///
///     static func makeDefaultStyleBody(configuration: LabeledViewConfiguration) -> some View {
///         HStack {
///             configuration.label
///
///             configuration.content
///         }
///     }
/// }
///
/// extension View {
///     func labeledViewStyle<Style: LabeledViewStyle>(_ style: Style) -> some View {
///         modifier(LabeledViewStyleModifier(style))
///     }
/// }
/// ```
///
/// Now imagine you need a "vertical" style that uses a `VStack` rather than an `HStack`.
/// With a custom style you can achieve this in a performant and type safe way.
/// Custom styles have access to all properties of the original ``StyledView``.
///
///     struct VerticalLabeledViewStyle: LabeledViewStyle {
///         func makeBody(configuration: Configuration) -> some View {
///             VStack {
///                 configuration.label
///
///                 configuration.content
///             }
///         }
///     }
///
/// Now imagine you need a "bordered" style that uses the existing or default style but also adds
/// a border. You can achieve this by returning another ``StyledView`` in the custom style body.
/// This showcases the major benefit with the view style approach as it allows for multiple styles
/// to be composed and reused together. The ``StyledView`` used within custom style body
/// will use the next ``ViewStyle`` if one exists, or the default style - which is the
/// `makeDefaultStyleBody(configuration:)` of the ``StyledView``.
///
///     struct BorderedLabeledViewStyle: LabeledViewStyle {
///         func makeBody(configuration: Configuration) -> some View {
///             LabeledView(configuration)
///                 .border(Color.red)
///         }
///     }
///
/// Now that you have created some custom styles, you can apply them with the style modifier.
/// Styles are composable which means the order you apply them does matter.
///
///     var body: some View {
///         VStack {
///             LabeledView {
///                 Text("Label")
///             } content: {
///                 Text("Content")
///             }
///             .labeledViewStyle(VerticalLabeledViewStyle())
///
///             LabeledView {
///                 Text("Label")
///             } content: {
///                 Text("Content")
///             }
///             .labeledViewStyle(VerticalLabeledViewStyle()) // Applied 1st
///             .labeledViewStyle(BorderedLabeledViewStyle()) // Ignored
///
///             LabeledView {
///                 Text("Label")
///             } content: {
///                 Text("Content")
///             }
///             .labeledViewStyle(BorderedLabeledViewStyle()) // Applied 1st
///             .labeledViewStyle(VerticalLabeledViewStyle()) // Applied 2nd
///         }
///     }
///
@attached(peer, names: suffixed(Configuration), suffixed(Body), suffixed(Style), prefixed(Styled), suffixed(StyleModifier), suffixed(DefaultStyle))
@attached(member, names: named(_body), named(init), named(Configuration))
public macro StyledView() = #externalMacro(module: "EngineMacrosCore", type: "StyledViewMacro")

/// A protocol intended to be used with the ``StyledView()`` macro to define a
/// ``ViewStyle`` and all its related components.
public protocol StyledView: PrimitiveView where Body == Never {

    /// The properties of the view passed to a style, generated by the macro.
    associatedtype Configuration

    /// The type of view representing the root body that styles are resolved within.
    associatedtype ResolvedStyleBody: View = Never
    /// Optionally implement to provide a root body that every style is resolved within,
    /// such as to add a modifier that should apply regardless of the style.
    ///
    /// Return the `Styled<Name>` view, created from the `configuration`, to resolve the
    /// current style.
    @ViewBuilder @MainActor @preconcurrency static func makeResolvedStyleBody(configuration: Configuration) -> ResolvedStyleBody

    /// The type of view representing the body of the default style.
    associatedtype DefaultStyleBody: View
    /// Creates the body of the default style, used when no other style is applied.
    @ViewBuilder @MainActor @preconcurrency static func makeDefaultStyleBody(configuration: Configuration) -> DefaultStyleBody

    associatedtype _Body: View
    @ViewBuilder @MainActor @preconcurrency var _body: _Body { get }
}

extension StyledView where ResolvedStyleBody == Never {

    public static func makeResolvedStyleBody(configuration: Configuration) -> Never {
        fatalError("makeResolvedStyleBody() should not be called on \(String(describing: Self.self))")
    }
}

extension StyledView {

    private nonisolated var content: StyledViewBody<Self> {
        StyledViewBody(content: self)
    }

    public nonisolated static func makeView(
        view: _GraphValue<Self>,
        inputs: _ViewInputs
    ) -> _ViewOutputs {
        StyledViewBody<Self>._makeView(view: view[\.content], inputs: inputs)
    }

    public nonisolated static func makeViewList(
        view: _GraphValue<Self>,
        inputs: _ViewListInputs
    ) -> _ViewListOutputs {
        StyledViewBody<Self>._makeViewList(view: view[\.content], inputs: inputs)
    }

    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    public nonisolated static func viewListCount(
        inputs: _ViewListCountInputs
    ) -> Int? {
        StyledViewBody<Self>._viewListCount(inputs: inputs)
    }
}

private struct StyledViewBody<Content: StyledView>: View {
    nonisolated(unsafe) var content: Content

    var body: some View {
        content._body
    }
}

@frozen
public struct _DefaultStyledView<Content: StyledView>: View {

    @usableFromInline
    var configuration: Content.Configuration

    @inlinable
    public init(_ configuration: Content.Configuration) {
        self.configuration = configuration
    }

    public var body: some View {
        Content.makeDefaultStyleBody(configuration: configuration)
    }
}
